### ISSUE TITLE
Question on loading csv file with data through JavaScript

### ISSUE THREAD

**Issue by pcm32** [escher/escher-demo#2]
Hi there and thanks for the terrific work on Escher!

I'm trying an static site where I want to preload some data for the user. Original reaction data comes from another process as CSV in a format like this:

| ID   | Minimum |
|------|---------|
| Rpgi | 0.373   |
| Rpfk | 0.411   |

This file sits on the same folder as the index, and so I load it like this (rxn_data.csv):

```
<script>
     d3.json('metabolic_map.json', function(error, data) {
       if (error) console.warn(error);
       if (data) {
          d3.csv('rxn_data.csv', function(rxn_error, rxn_data) {
		if (rxn_error) console.warn(rxn_error)
		console.log(data)
		var reformatted_rxn_data = {};
		rxn_data.forEach(function(d) {
			reformatted_rxn_data[d.ID] = d.Minimum
		});
		var options = { menu: 'all', fill_screen: true };
		var b = escher.Builder(data, null, null, d3.select('#map_container'), options);
		console.log(reformatted_rxn_data);
		b.set_reaction_data(reformatted_rxn_data);
		});
	  }
       });
    </script>
```

Currently I need to transform the generated JSON that d3 creates from my csv. I see that on escher.js you have a method called `load_json_or_csv`, but I don't seem to be using it correctly (to avoid doing the transformation myself. My problems seem to come in the way that I'm feeding the file. For instance:

```
escher.utils.load_json_or_csv('rxn_data.csv', escher.data_styles.csv_converter, function(error, rxn_data) 
  {
	if (rxn_data) {
		b.set_reaction_data( rxn_data )
	}
   }		
)
```

doesn't seem to work as it is expecting the first argument to be a Blob already... 

How would you do it to read the data from the CSV file but reusing your load_json_or_csv method to avoid my manual JSON transformation? I don't do JS very often.

I know that I could transform the CSV into JSON through python for instance, but all of these is currently inside a container, and if I could avoid adding python it would be very useful!

Thanks!

**Comment by zakandrewking** [comment]
Unfortunately you're right that it uses the [FileReader API](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) to load a file reference from a blob.

You could try to [create a Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) from your loaded data and pass it into `load_json_or_csv`. But your existing code is probably simpler and easier to maintain.
