### ISSUE TITLE
Where are the values of the reactions defined ?

### ISSUE THREAD

**Issue by LeducH** [escher/escher-demo#3]
Hi @zakandrewking  I was wondering how the values are defined reactions in the knockout example. 
[link](https://escher.github.io/escher-demo/knockout/).
 Looking over into the e.coli jsons and the `knockout.js` I found that in line 82 you check `result.f < 1e-3)`. When I looked into the json files `E coli core.Core metabolism.json` and `E coli core.json` I was wondering which json tag returns the value for the reactions?

**Comment by zakandrewking** [comment]
I'm not quite sure what you mean.

If you are thinking about the reaction data, i.e. flux prediction values, those are generated by the GLPK optimization library and are in the `result.x` object

**Comment by LeducH** [comment]
Thanks for the reply. Let me make clear what I wan to do: I want to build my own pathway with custom click events. More precisely I want to create path way so that if I click on reactions I can change the growth rate. 

I checked the `kockout.js` and i would say that the function `optimze_loop` handles most of what I want to do.  For me the object `var result = optimize(problem); `  is unclear how it is instantiated and how it works. 

As a concrete question can I just replace the maps to use the same knockout function? And why do I need two maps? In your example you have `E coli core.Core metabolism.json` and  `/E coli core.json`. I would assume that I need to use the map builder but  why do I need two maps.

**Comment by zakandrewking** [comment]
`optimize()` uses glpk.js, which has the same API as GLPK: https://www.gnu.org/software/glpk/

I am happy to answer specific questions about what is happening.

There are not two maps. The first one is the map, which specifies the layout, and the second one is the *model*, which would be used to draw new reactions on the map. More detail here: https://escher.readthedocs.io/en/stable/escher_and_cobrapy.html#maps-and-models

**Comment by LeducH** [comment]
Thank you for your response, Zak. 

I will have I look into the API of GLPK. 

If I understand correctly the model and map are in Json format and serve different purposes. Where the map only handles the vertices and edges the model in Cobra handles the reactions. 

Therefore if I understand it correctly to create my own map with reactions I should load the reactions from [Here](https://escher.readthedocs.io/en/stable/getting_started.html#example-data-files)  in the map builder. Add nodes/reactions then I can export the Json of the map. 

Then my questions is: How to I add the handling of the javascript events of each clicks so that I can show the level of growth as in knockout example? What are the concrete steps for this?

**Comment by zakandrewking** [comment]
the click events are registered here:

https://github.com/escher/escher-demo/blob/833c0e1de44d4a9456fa50c293a094b389c21be0/knockout/knockout.js#L103
